
study:
  name: Camilleri18_eMDN

  keyword:
    - neural correlates

  principal_investigator: s.weis@fz-juelich.de

  #purpose: ***
  # start_date: ***
  # end_date: ***

  contributor:
    - j.camilleri@fz-juelich.de

  #funding:
  #  - DFG

dataset:
  name: Camilleri18_eMDN
  location: http://inm7.de/datasetsBnB_USER/Camilleri/TO_ARCHIVE/Camilleri/MutliState_eMDN
  author:
    - j.camilleri@fz-juelich.de


  #description: ***

  #standard:
  #  - dicom

  #keyword:
  #  - fMRI

  #funding:
  # - <ex>NIH</ex>


publication:
  - title: "Definition and characterization of an extended multiple-demand network"
    author:
      - j.camilleri@fz-juelich.de
      - v.mueller@fz-juelich.de
      - fox@uthscsa.edu
      - alaird@fiu.edu
      - f.hoffstaedter@fz-juelich.de
      - tobias.kalenscher@hhu.de
      - s.eickhoff@fz-juelich.de

    year: 2018
    doi: 10.1016/j.neuroimage.2017.10.020
    publication: Neuroimage
    volume: 165
    pages: 138‐147

person:
  j.camilleri@fz-juelich.de:
    given_name: Julia
    last_name: Camilleri
    title: Dr.

  v.mueller@fz-juelich.de:
    given_name: Veronika
    last_name: Müller
    title: Dr. rer. med.

  fox@uthscsa.edu:
    given_name: Peter T
    last_name: Fox
    orcid-id: https://orcid.org/0000-0002-0465-2028
    title: M.D.

  alaird@fiu.edu:
    given_name: Angela R.
    last_name: Laird
    title: Prof. Dr.

  f.hoffstaedter@fz-juelich.de:
    given_name: Felix
    last_name: Hoffstaedter
    title: Dr.

  tobias.kalenscher@hhu.de:
    given_name: Tobias
    last_name: Kalenscher
    title: Prof. Dr.

  s.eickhoff@fz-juelich.de:
    given_name: Simon
    last_name: Eickhoff
    title: Prof. Dr.

  s.weis@fz-juelich.de:
    given_name: Susanne
    last_name: Weis
    title: PD Dr.

